### ISSUE TITLE
04-world-series-home-field

### ISSUE THREAD

**Issue by murraymegan** [yasiwang0315/Probability-and-Inference-Portfolio-Wang-Yasi#3]
For Question#1 include "What is the difference in probabilities?"

**Comment by murraymegan** [comment]
Also "explain the solution in a way that is accessible to a general audience." This would include interpreting what the difference in probabilities means.

**Comment by murraymegan** [comment]
If you have any questions please message me on Slack.

**Comment by yasiwang0315** [comment]
> For Question#1 include "What is the difference in probabilities?"

Hi Megan, I've added the difference and explained what it means~ Thx~

**Comment by yasiwang0315** [comment]
I've added the difference and explained what it means~ Thx~

**Comment by murraymegan** [comment]
PASS
