### ISSUE TITLE
06-order-statistics

### ISSUE THREAD

**Issue by murraymegan** [yasiwang0315/Probability-and-Inference-Portfolio-Wang-Yasi#5]

**Comment by murraymegan** [comment]
While very close the following statement is not true "The CDF and ECDF are perfectly overlapped." I would say "The CDF and ECDF are almost perfectly overlapped." Very good code. I would also like you to include an explanation for the last question. How are the 2 distributions different?

**Comment by yasiwang0315** [comment]
> While very close the following statement is not true "The CDF and ECDF are perfectly overlapped." I would say "The CDF and ECDF are almost perfectly overlapped." Very good code. I would also like you to include an explanation for the last question. How are the 2 distributions different?

I changed the statement and added some explanations~ Thanks, Megan~

**Comment by yasiwang0315** [comment]
I changed the statement and added some explanations~

**Comment by murraymegan** [comment]
For this sentence "As the X100 increases, the probability increases and gets stable at 1 when X100 equals to 0.4." a better wording is "The probability increases and becomes equivalent to 1 when X100 **is greater than or equal to 0.4.**" Also please change this "As for probability, it increases and gets stable at 1 when X1 equals to -2." to have the right interpretation. Everything else looks great!

**Comment by yasiwang0315** [comment]
@Megan-Hollister I changed the interpretation~ Thanks!

**Comment by murraymegan** [comment]
PASS
